# For more info on HTTP files go to https://aka.ms/vs/httpfile
@organization=YOURORGANIZATION
@teamproject=YOURTEAMPROJECT
@apiversion=7.0
@azdopat=YOURPAT
@groupID=123

# GET all variable groups

GET https://dev.azure.com/{{organization}}/{{teamproject}}/_apis/distributedtask/variablegroups?api-version={{apiversion}}
Authorization: Basic {{azdopat}}

###

# GET variable groups with specific ID

GET https://dev.azure.com/{{organization}}/{{teamproject}}/_apis/distributedtask/variablegroups/{{groupID}}?api-version={{apiversion}}
Authorization: Basic {{azdopat}}
